include:
  - project: $CATALOG_PATH
    file: vault-ci.yml
    ref: main
  - project: $CATALOG_PATH
    file: kaniko-ci.yml
    ref: main

default:
  image: alpine:latest

variables:
  REGISTRY_URL: ${REGISTRY_HOST}/${PROJECT_PATH}

stages:
  - read-secret
  - docker-build

read_secret:
  stage: read-secret
  extends:
    - .vault:read_secret

build:
  variables:
    WORKING_DIR: ./
    DOCKERFILE: ./Dockerfile
    IMAGE_NAMES: grist-sync-api:${CI_COMMIT_SHORT_SHA} grist-sync-api:${CI_COMMIT_REF_NAME}
    EXTRA_BUILD_ARGS: --registry-mirror registry.dso.interieur.rie.gouv.fr/dockerhub
  stage: docker-build
  extends:
    - .kaniko:build-push
  # Triggers job only if a file in the client directory changed in current commit
  # rules:
  #   - changes:
  #     - client/**/*